#!/bin/bash

echo "🚀 GitHub Deployment Commands for React + Supabase Product Manager"
echo "=================================================="
echo ""
echo "1️⃣ First, create a new repository on GitHub:"
echo "   👉 Go to: https://github.com/new"
echo "   📝 Repository name: gorev-18 (or react-supabase-product-manager)"
echo "   📝 Description: React + Supabase Product Management Panel with Authentication"
echo "   🔓 Keep it Public for easy deployment"
echo "   ❌ Don't initialize with README (we already have one)"
echo ""
echo "2️⃣ After creating the repository, copy and run these commands:"
echo ""
echo "# Replace YOUR_USERNAME and REPO_NAME with your actual values"
echo "git remote add origin https://github.com/YOUR_USERNAME/REPO_NAME.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "3️⃣ Deploy to Vercel (Recommended):"
echo "   👉 Go to: https://vercel.com"
echo "   🔗 Sign in with GitHub and import your repository"
echo "   ⚙️  Add these environment variables:"
echo "       VITE_SUPABASE_URL=https://cgrgxqrgowevvjpjbjkk.supabase.co"
echo "       VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncmd4cXJnb3dldnZqcGpiamtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDIxMTQsImV4cCI6MjA2NzIxODExNH0.3NnolMMDm2RzTwFo85ztRB-XEngpkaQgPNMLHYZ3Jts"
echo ""
echo "4️⃣ Configure Supabase for production:"
echo "   👉 Go to: https://supabase.com/dashboard/project/cgrgxqrgowevvjpjbjkk"
echo "   ⚙️  Authentication > URL Configuration:"
echo "       - Add your production URL to 'Site URL'"
echo "       - Add production URL to 'Redirect URLs'"
echo ""
echo "🎉 Your app will be live and ready for the June 4, 2025 deadline!"
echo ""
echo "📋 Project Status:"
echo "✅ All code committed to Git"
echo "✅ Production build working"  
echo "✅ Supabase integration ready"
echo "✅ Ready for deployment" 